spring:
  application:
    name: SecureSign

server:
  port: 8080

logging:
  level:
    es.faustino.securesign: DEBUG

securesign:
  keystore-password: ${SECURESIGN_KEYSTORE_PASSWORD:password-dev-default}
  alias-ecdsa: securesign-ecdsa
  alias-ed25519: securesign-ed25519
