spring:
  application:
    name: SecureSign

server:
  port: 8080

logging:
  level:
    es.faustino.securesign: DEBUG

securesign:
  keystore-password: ${SECURESIGN_KEYSTORE_PASSWORD:gmId2e7xiGu9JPIMXep3M0PTe4VvZrPW4z0ej4KKu24=}
