spring:
  application:
    name: SecureSign

server:
  port: 8080

logging:
  level:
    es.faustino.securesign: DEBUG

securesign:
  keystore-password: ${SECURESIGN_KEYSTORE_PASSWORD:securesign-dev-password}